### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by miathedev** [Espher5/smart_home#1]
Hi Michelangelo,

short question to task 3.
Did i understood the light behavior correct?

-  If the light is on, it never turns off. until once - there is no presence detected anymore, because then it turns off anyways. 
- It doesn't matter if the room gets lit again by ambient light from outside during a light on phase. The light will stay on until no presence is detected.

I am asking because that sounds weird to me.

**Comment by Espher5** [comment]
Hi Mia,

you're right, in normal circumstances you would certainly consider the ambient light changes after the light turns on (if you're familiar with it, imagine the Arduino loop function, where at every iteration we would check for the light level, as well as the other measurement.).
Here we perform just a check at the beginning where if the light in the room is >= lux we don't turn on the light (or we turn it off if it was already on, maybe from a previous method call).

We do this for the sake of unit testing; we just implement the individual functionalities to make it easier to test them individually.
